name: Go
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v1
        with:
          go-version: 1.22
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          go mod download
      - name: Test
        run: go test -v -covermode atomic -coverprofile=profile.cov ./...
